### ISSUE TITLE
[INFO] Alignment Mechanism

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#101]
So I have tried multiple times to fix alignment issues, and I think it is time to put this issue down once and for all.
I'm going to document what I believe is the way that alignment works, and then will implement it when I get time (hopefully this weekend). I think what we have currently is *pretty* close, but there are some small issues still persisting, and lot of the alignment code is quite ad-hoc or alignment is performed multiple times so the logic has become quite obscure.

There are two different methods of alignment. **Relative** alignment and **absolute** alignment.

**Relative alignment:**
*This applies to all fields within a struct.*
The alignment is relative to the start location of the current struct.

**Absolute alignment:**
*This applies to any struct that is in a list*
The alignment is relative to the start of the file.

In general we have the following alignment values:
Most structs align at *0x4* with a few exceptions:
 - booleans - none
 - strings - none
 - Vector4f's & Colours - 0x10
 - Most NMSTemplate objects - 0x8 [NOTE: this needs to be checked further...]
[Expection: structs that are only 0x4 long??]
 - List headers - 0x8

To ensure that the correct type of alignment is performed I think we need to add an extra argument to the (de)serializeValue function: `bool inlist`

We also need to ensure that the settings values are passed into the (de)serialization functions as the alignment of fields that are NMSTemplate's is an attribute of the struct, not the field.

I think most of these issues have been fixed, but it will be good to have a proper check over everything and make sure it is all working as intended and we can finally stop having to deal with stupid alignement issues (yay!!)

**Comment by GaticusHax** [comment]
study this: http://www.catb.org/esr/structure-packing/
and this: https://en.wikipedia.org/wiki/Data_structure_alignment

The way that alignment is handled in NMSTemplate is just not correct and is spread out over the code. Problems will continue pop up as changes are made to fix other alignment problems, until all the sizes and alignment are eventually hard-coded.

It needs to be encapsulated and the proper rules need to be implemented to calculate member, struct and array alignment, member offsets and type sizes.

**Comment by chrispurnell** [comment]
I've been looking at fixing the alignment issues that libmbin currently has.  The first step is to make sure every class has the correct alignment annotation. But in trying to calculate the alignments I have found out that the alignment of some strings is 8 bytes.  It appears to be ID strings that have such an alignment.  I have yet to find a 16 byte strings that is not 8 byte aligned and most 32 byte stings are also 8 byte aligned.  The rest appear to be 1 byte aligned as expected.  The problem is identifiying witch of these 32 byte stings are 8 byte aligned and which of them are 1 byte aligned.

**Comment by monkeyman192** [comment]
Yeah, I have noticed this too. They are distinguishable within the exe, so that is fine, but my main issue is a way to on compile add the alignment attribute to every class. I don't know enough c# to know how to do this, but ideally what would happen is that on compile we would have some code which adds the alignment attribute to every class in the project in a calculated way. If I knew how to do this then we'd be in business...

**Comment by chrispurnell** [comment]
I would suggest instead of adding them on compile have a test that checks that they are correct.

**Comment by chrispurnell** [comment]
I've also noticed that there are some gaps filled by padding bytes that also effect the alignment of the class.  It appears that in a few cases there is a field that is not saved in the mbin but leaves space and can effect the alignment.
Also the 4 byte default does not make much sense when most of the classes have an 8 byte alignment.

**Comment by monkeyman192** [comment]
> 
> 
> I would suggest instead of adding them on compile have a test that checks that they are correct.

The issue is that alignments can change, and I also don't really want to write down the alignments of well over 1000 classes by this point.

**Comment by chrispurnell** [comment]
But how many classes will have their aligment change because of an update?

**Comment by monkeyman192** [comment]
Honestly, I am not really sure. However we do it though we are going to need a script which will actually determine the alignments, because there are just so many of them. If we can then have this as part of the build pipeline then it doesn't really matter and we don't have to care about it...

**Comment by chrispurnell** [comment]
The easiest way to calculate the alignments is with a c# program that goes over all the classes using reflection.  This required libmbin be compiled which is why I sugested making it a test.

I have written such a program and have used it to add the alignment annotation to all classes in toolkit and gamecomponents of a libmbin based on 3.21.  However it is still giving 282 incorrect alignments.  That goes down to 54 with an exception for 16 byte strings.  Add a similar exception for 32 byte stings and that numbers goes to 23.  20 of which are different classes.  The 3 common classes are the 3 in toolkit which are a 128 byte sting followed by a 4 byte padding which all need a 4 byte alignment.

I'm thinking about adding an alignment to the field annotations where needed for the alignment calculations.

**Comment by monkeyman192** [comment]
Ok, so after looking in the exe and the source code I see what you mean about the 0x10 byte strings. They do indeed all seem to be aligned at 0x8.
The 0x20 byte strings we can compare our source with the exe to determine which are aligned and which are not. It may be worth adding a second class for this aligned 0x20 string so that we can handle this correctly.

I was looking into source generators last night but they are a c# 9 only feature which requires .NET 5 which might not be the best thing to start trying to use since it is quite new...

**Comment by chrispurnell** [comment]
Do you have automated tools for examining the exe?  I'm currently searching through a disassembly and section hex dump by hand.

**Comment by monkeyman192** [comment]
I have some scripts I use with IDA, and Wberto has some scripts that he uses with ghidra. I have been meaning to put them into this repo so others can use but because of occasional updates they become outdated. I'll try get them up soon though since I have just updated mine recently for the latest version of the exe...

**Comment by chrispurnell** [comment]
I've put my program to calculate the alignments up as a github gist.
[https://gist.github.com/chrispurnell/9a6bab6bc81ed1e9844691720fe3a22c](url)
