### ISSUE TITLE
[Update] Changes for 3.41 (6728119)

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#332]
# Structs with internal changes | GUID | NameHash | Size | Fields:
- [x] GcAtlasDiscoveryData                               | 0x8B10056FD8A6F907| 0x34272E24BB717FCB| 0x48   | 4 
- [ ] GcAtlasRecvBaseImages                              | 0x86590CF5159C1D17| 0xC3C14D18029FA426| 0x28   | 5 
- [ ] GcAtlasSendSubmitMessage                           | 0x2A2E2F3930C60758| 0x3F2A102EA6C0D44B| 0xD0   | 2 (+2)
- [x] GcAtlasSendSubmitMonument                          | 0xAEBC854578DE6E33| 0xF4282F250D0EEBDB| 0x1D0  | 4 
- [ ] GcAtlasSendSubmitSeasonStageCompleted              | 0x5E31B1DF93F2028A| 0x28ADD037AEDE77EB| 0x18   | 3 (+3)
- [x] GcCostProduct                                      | 0xA3FCD9E831043706| 0xE90BC34FB3DEA4D7| 0x20   | 3 
- [ ] GcCustomisationGroup                               | 0xC1D1716D86A52E9B| 0x0B5A01AE676FD46D| 0xA8   | 9 
- [ ] GcDamageMultiplierLookup                           | 0x31B87E042D974AFE| 0x792FD0F5EBBA55E9| 0x28   | 3 
- [ ] GcDefaultMissionProduct                            | 0x602DB248C9FAB5D3| 0x1F78606838C7F310| 0x4    | 1 
- [ ] GcFrigateInteractionAction                         | 0xAD1975B8FA694E7C| 0xD1183794AF82FF99| 0x28   | 2 
- [ ] GcGalaxyWaypoint                                   | 0xFF20FABD019768C3| 0x562052A8272CC4A3| 0x38   | 3 
- [ ] GcGalaxyWaypointTypes                              | 0x895A0820CE617DE4| 0xF808614547AF2B25| 0x4    | 1 
- [ ] GcGenericIconTypes                                 | 0x87544BCF24578A79| 0xA4091406380F5113| 0x4    | 1 
- [ ] GcInventoryBaseStat                                | 0xCB86CFCCBC8AEF97| 0x88CEC164B6BD4ACC| 0x30   | 3 
- [ ] GcInventoryBaseStatBonus                           | 0xFB1C90CB69054C1C| 0xCBEE12530E8A51CD| 0x8    | 2 
- [ ] GcJourneyCategory                                  | 0x1D45AD369A7A2FE8| 0x88F1E142115EF824| 0x188  | 9 
- [ ] GcMarkerComponentData                              | 0x4F3FB3E99D075F87| 0x499B7E363F46B54F| 0x38   | 7 
- [x] GcMessageProjectileImpact                          | 0xFDB58E6F6DB84456| 0x7EBC25FE326CF24B| 0x50   | 10 (+1)
- [ ] GcMissionBoardOptions                              | 0xCA65A99C3B10391B| 0xDD272E15749CCDF5| 0x80   | 15 
- [x] GcMissionConditionEventRequiresRGB                 | 0x9C6FF0332EAD43B3| 0x36CE03A85A61CBFB| 0x28   | 3 
- [x] GcMissionConditionHasEndpointForEvent              | 0x98657E8C7DFA59B6| 0x9C35F879928BF0CE| 0x28   | 2 
- [x] GcMissionConditionHasFuel                          | 0xAFC26734D6BF2110| 0x2A8282CD4FA96596| 0x18   | 3 
- [x] GcMissionConditionIsScanEventActive                | 0x9BFB3B6D5FFE320A| 0xDF80EC28C687305E| 0x28   | 2 
- [x] GcMissionConditionIsScanEventOnCurrentPlanet       | 0x79C865AEDFE0C003| 0xEB5EF017837D2565| 0x28   | 2 
- [x] GcMissionConditionLocation                         | 0x0DBD0CB8155C933E| 0x64A394B637C25752| 0x4    | 1 
- [x] GcMissionConditionNearScanEvent                    | 0xE31955C81647FC37| 0x8F7E57B730A9C7F8| 0x28   | 4 (+1)
- [x] GcMissionConditionWeaponMode                       | 0x3FA159601A988735| 0x798B3001AC5A7114| 0x4    | 1 
- [x] GcMissionConsequenceRemoveCommunicatorMessage      | 0x33D4A6F29AFA50E4| 0xE2DF0C2D3E6E3BF8| 0x20   | 1 
- [x] GcMissionConsequenceRemoveScanEvent                | 0xD40930210BB52C9F| 0x66D8F2741332E444| 0x20   | 1 
- [x] GcMissionPageHint                                  | 0xBAADE82FFF5952D4| 0xBC45706D394C0853| 0x4    | 1 
- [x] GcMissionSequenceEndScanEvent                      | 0x59E934EAC79B537E| 0x0D15F5E0AAE5AA74| 0xA0   | 2 
- [x] GcMissionSequenceGatherForRefuel                   | 0x913EE552C721D530| 0x9FA5A1E5E026A5B3| 0x108  | 4 
- [x] GcMissionSequenceGatherForRepair                   | 0xDC758A93BA54A2C0| 0x535215E1DEB68BB2| 0x118  | 4 
- [x] GcMissionSequenceGetToExpedition                   | 0x20982378EF686841| 0xB3C5F69D62F6CA73| 0x1A8  | 5 
- [x] GcMissionSequenceReward                            | 0x2A7E5A2390BD677B| 0x7471FD77815538C2| 0x118  | 4 
- [x] GcMissionSequenceStartScanEvent                    | 0x90CF75D7BA76F02A| 0x84E26BAA3B367507| 0xB0   | 6 
- [x] GcMissionSequenceStartScanEventSpecific            | 0xCDB543AB27830175| 0x83CCE421927A9559| 0x100  | 6 
- [x] GcMissionSequenceVehicleScan                       | 0x79972371778E4C36| 0x0D9BAAE731EB23B1| 0x120  | 3 
- [x] GcMissionSequenceWaitForPhoto                      | 0x812B41B01DFCC437| 0x2EB82866D685EFBF| 0x240  | 8 
- [x] GcMissionSequenceWaitForRefuel                     | 0xCFC9CC53C7F79504| 0x25696B35BE341F6C| 0x108  | 4 
- [x] GcMissionSequenceWaitForRepair                     | 0x71CA623B59319277| 0x079652C883CA60AE| 0x104  | 3 
- [x] GcMissionSequenceWaitForStat                       | 0x2BEFBFF68BD985C8| 0x197E91849165F7F4| 0x128  | 5 
- [x] GcModBasePart                                      | 0xF1BD945926480534| 0x6A104C45E1F1638D| 0x6D0  | 3 
- [ ] GcMultitoolData                                    | 0x5A1C57036035083D| 0x2AF78E5732410B4F| 0x1C0  | 8 
- [x] GcPhotoFlora                                       | 0x324E5B346B2F2882| 0x2D2DE27512E8C450| 0xC    | 3 
- [x] GcPhotoPlant                                       | 0x820E799003AAABBF| 0xEFC8FCE1F6004590| 0x4    | 1 
- [x] GcPlayerExperienceSpawnTable                       | 0x900EB9C7527F9E30| 0xA1B202DE9A10A705| 0x30   | 6 
- [ ] GcProceduralProductData                            | 0x54E33BADFEB9926F| 0xC449167C8DE081CD| 0x8D0  | 8 
- [ ] GcProceduralTechnologyData                         | 0xEF7C6107950E0E27| 0x6B8472FADE3C492C| 0x290  | 15 
- [ ] GcProceduralTechnologyStatLevel                    | 0xCF00C7D7A791C49D| 0xF41CD566C844982A| 0x14   | 5 
- [ ] GcRealityIcon                                      | 0x53465DE5A63828B1| 0x28AB5E6C29FCA8E5| 0xA8   | 2 
- [ ] GcRefinerRecipe                                    | 0xA2F08B28C5066577| 0x309D52938C546138| 0x70   | 6 
- [x] GcRepairTechData                                   | 0xFF031B966938227C| 0xD610CA25729E63C3| 0x1A0  | 4 (+1)
- [x] GcRewardActivateCorruptedDrone                     | 0xF032A4340F8381ED| 0xCA4D2B1DC7089D9D| 0x28   | 3 
- [x] GcRewardAdvancePortalState                         | 0x6F026107F210237D| 0x54AAB4996FB2487B| 0x20   | 1 
- [x] GcRewardCrashSiteFly                               | 0xC90DA1C6AAC78894| 0x28670AE3B159B8FC| 0x20   | 1 
- [x] GcRewardMissionMessageSeeded                       | 0x867F7373ED1252F6| 0x56DEE85C9E579653| 0x18   | 3 (+1)
- [x] GcRewardOpenFreeFreighter                          | 0xB6076343E576F32D| 0x4DD6C74BA4B6AD5A| 0x48   | 3 
- [x] GcRewardScanEvent                                  | 0xC4540B52B2725A62| 0xD6D2BF5DDCCD9F49| 0x28   | 4 
- [x] GcRewardSpecificSpecial                            | 0xA4AFBFF9DFE44876| 0xCF9FC45A7B70BB85| 0x38   | 3 
- [x] GcRewardSpecificTech                               | 0xFEB1FC5E038A21E6| 0xDABE4D9A95799081| 0x18   | 3 
- [x] GcRewardSpecificTechFromList                       | 0x7C282CE33A844ED7| 0xF33640B1865E5E4B| 0x18   | 3 
- [ ] GcScanEventSave                                    | 0x0E527F6FF8F5898E| 0x434C17159AF37265| 0x80   | 10 
- [ ] GcScannableComponentData                           | 0x8B670E1642F40DC2| 0x74BA808E86F0EC01| 0x80   | 18 
- [ ] GcScannerIcon                                      | 0x818EF9AAA4C46A66| 0x85905E340468CC13| 0x10C  | 3 
- [ ] GcScannerIconTypes                                 | 0xD871C82A57BD4AE7| 0x8A4027FC041677F0| 0x4    | 1 
- [ ] GcShipWeaponData                                   | 0xB164A93BB44FF0B4| 0x73BA1311CF8E1962| 0x40   | 9 
- [x] GcStats                                            | 0xE815AF4E17216578| 0x9C20970E839B65D9| 0x10   | 1 
- [ ] GcStatsBonus                                       | 0xEE5DBAAC1719BE35| 0xBAC710ADD80D9C59| 0xC    | 3 
- [ ] GcStatsEntry                                       | 0x8747A1C16EC24E65| 0x4309D65C13EEC689| 0x40   | 6 
- [ ] GcStatsGroup                                       | 0xEDB19955BFB2F65E| 0xEB5E59FB895AFF06| 0xA8   | 3 
- [x] GcStatsTypes                                       | 0xBE9642E402E2836E| 0x003E6292A999E2A6| 0x4    | 1 
- [x] GcTargetMissionSurveyOptions                       | 0xC5BCD08BAB773978| 0x4E7A7CEB00A9346B| 0x198  | 5 (-1)
- [x] GcTechnologyTypes                                  | 0xFEDC3500FE067BD6| 0x324956CF456BD3E1| 0x10   | 1 
- [ ] GcTerrainEditing                                   | 0xE0D6A6545E3C505E| 0x4686D0FAC0A1B9EC| 0x98   | 30 
- [ ] GcTradeSettings                                    | 0xCFFA3BDDF2A0BDDA| 0x4B63CD1B58DAF5A4| 0xDA8  | 19 
- [x] GcVehicleScanTableEntry                            | 0x08F71353B2FED771| 0xBAC942D350F478B1| 0xC8   | 4 

# Structs with a size change:
- [x] GcAISpaceshipGlobals                               | old: 0xDD0  | new: 0xE30  | GUID: 0x799F4D491CC28E95| Fields: 346 (+1)
- [ ] GcAtlasRecvActiveFeaturedBasesQuery                | old: 0x18   | new: 0x20   | GUID: 0x42D07F5EA314B2B0| Fields: 2 
- [x] GcAtlasRecvBaseList                                | old: 0x30   | new: 0x38   | GUID: 0x29046730D3CB288A| Fields: 4 
- [x] GcAtlasRecvBaseQueryList                           | old: 0x20   | new: 0x28   | GUID: 0xB51027B0F5F84DDF| Fields: 3 
- [ ] GcAtlasRecvBasic                                   | old: 0x10   | new: 0x18   | GUID: 0x74F43D9D795E8787| Fields: 2 (+2)
- [ ] GcAtlasRecvDiscoveryExact                          | old: 0x300  | new: 0x310  | GUID: 0x5C7C6013F8BCE2AB| Fields: 3 (+3)
- [x] GcAtlasRecvFeaturedBasesQueryList                  | old: 0x20   | new: 0x28   | GUID: 0xC51628B104A72A46| Fields: 3 
- [ ] GcAtlasRecvMonumentList                            | old: 0x1A0  | new: 0x1B0  | GUID: 0xE7251104BD32F87E| Fields: 3 
- [ ] GcAtlasRecvTotalContribution                       | old: 0x18   | new: 0x20   | GUID: 0x88D927C5D3ACE8D9| Fields: 3 
- [ ] GcAtlasRecvVoxel                                   | old: 0x50   | new: 0x58   | GUID: 0xAB31E38EB110A2EB| Fields: 3 
- [ ] GcAtlasSendChangeFeaturedBasesEnv                  | old: 0x18   | new: 0x20   | GUID: 0xA4BF39A04658FAB1| Fields: 2 
- [ ] GcAtlasSendMarkFeaturedBase                        | old: 0x48   | new: 0x50   | GUID: 0xC27C66754E23328B| Fields: 2 
- [ ] GcAtlasSendMarkFeaturedBaseWithImage               | old: 0x58   | new: 0x60   | GUID: 0x43B957129D1B95F6| Fields: 3 
- [ ] GcAtlasSendQueryActiveFeaturedBases                | old: 0x8    | new: 0x10   | GUID: 0x984230EA43944609| Fields: 1 
- [x] GcAtlasSendQueryBaseImages                         | old: 0x18   | new: 0x20   | GUID: 0xFEC2B020D496EB35| Fields: 2 
- [ ] GcAtlasSendRemoveFeaturedBases                     | old: 0x18   | new: 0x20   | GUID: 0x067E627F1BDA6FC4| Fields: 2 
- [ ] GcAtlasSendReport                                  | old: 0xA8   | new: 0xB0   | GUID: 0x2869871E836C6B06| Fields: 6 (+6)
- [ ] GcAtlasSendRequestBlob                             | old: 0x70   | new: 0x78   | GUID: 0x534F1EAF42644C4A| Fields: 4 (+4)
- [ ] GcAtlasSendRequestDiscoveryAllOnPlanet             | old: 0x20   | new: 0x28   | GUID: 0x6DFEB50FEF29FC7C| Fields: 2 (+2)
- [ ] GcAtlasSendRequestDiscoveryCategory                | old: 0x28   | new: 0x30   | GUID: 0x9102AD934E34EED9| Fields: 3 (+3)
- [ ] GcAtlasSendRequestDiscoveryExact                   | old: 0x50   | new: 0x58   | GUID: 0x79B8FBAA3C146C56| Fields: 2 (+2)
- [ ] GcAtlasSendRequestMonument                         | old: 0x20   | new: 0x28   | GUID: 0xD04C6FE608349B49| Fields: 2 (+2)
- [x] GcAtlasSendRequestTotalContribution                | old: 0x8    | new: 0x10   | GUID: 0x3D02503C2F082AFF| Fields: 1 
- [ ] GcAtlasSendRequestVoxel                            | old: 0x20   | new: 0x28   | GUID: 0x07B0C9934C1CF50C| Fields: 2 (+2)
- [x] GcAtlasSendSubmitBaseWithImage                     | old: 0x320  | new: 0x330  | GUID: 0x766BDAAD5AF729EC| Fields: 3 
- [x] GcAtlasSendSubmitDiscoveryExact                    | old: 0xD0   | new: 0xD8   | GUID: 0x2C9685FB3FF52145| Fields: 3 (+3)
- [x] GcFleetGlobals                                     | old: 0x16B0 | new: 0x1910 | GUID: 0x284B5EBC189D518E| Fields: 136 (+9)
- [x] GcFrigateClassCost                                 | old: 0x14   | new: 0x18   | GUID: 0x25C9483BA5237DCE| Fields: 1 
- [x] GcFrigateStats                                     | old: 0x60   | new: 0x68   | GUID: 0x05C119C6B02E613B| Fields: 2 
- [x] GcFrigateStatsByClass                              | old: 0x1E0  | new: 0x270  | GUID: 0x7CD92589ED95F1A0| Fields: 1 
- [x] GcFrigateTraitIcons                                | old: 0x500  | new: 0x580  | GUID: 0x69FFF37CCA5995E5| Fields: 1 
- [x] GcFrigateTraitStrengthByType                       | old: 0x320  | new: 0x370  | GUID: 0x7C932E4E8ECD9EE0| Fields: 1 
- [x] GcPassiveFrigateIncomeArray                        | old: 0xA0   | new: 0xC0   | GUID: 0xCFE1C74A7BD0885A| Fields: 1 
- [x] GcPlayerGlobals                                    | old: 0x1C80 | new: 0x1CA0 | GUID: 0xEF116EB2C021600F| Fields: 843 (+3)

# Structs with diff GUID (exe != MBIN):
- [x] GcCameraGlobals                                    | 0x5A97F710157A2074| 0x5F55D9DADA608A77
- [x] GcGalaxyGlobals                                    | 0xBED38FC0F18F4ABA| 0xE4A5856BEF1E74DA
- [x] GcGameplayGlobals                                  | 0xB36B01A8EEDB59BA| 0xB7CDA1B1ABAE281C
- [x] GcUIGlobals                                        | 0xC8CF05F1144F378E| 0xB03A4315276D77B4

# Structs with diff # of Fields | GUID | NameHash | Size | Fields:
- [ ] GcAtlasDiscovery                                   | 0x28F613BC51BF1666| 0x0886C03C3F3987F4| 0x2F0  | 7 (+7)
- [ ] GcAtlasSendRequestBases                            | 0xF8653D82867B12BE| 0x8224EED427CDE62A| 0x60   | 2 (-6)
- [x] GcFontTable                                        | 0xB9913A609DA490D3| 0xD77829A90743F12E| 0x420  | 1 (-7)
- [ ] GcMessageCrime                                     | 0x1CCB7BDC1ECBB02A| 0x0C64AF7F76101CD0| 0x30   | 5 (+2)
- [ ] GcMessageFiendCrime                                | 0x5873ED86AF6E466E| 0x037D134945C6DC0E| 0x20   | 4 (+1)
- [ ] GcMessageNPCBehaviourEvent                         | 0x4C926B203874A03B| 0x40F7E71C83A33DA0| 0x50   | 6 (+1)
- [ ] GcMessagePetBehaviourEvent                         | 0x306E8557E0A11798| 0x9465A52B8A2F9FD9| 0x70   | 7 (+1)
- [ ] GcResourceElement                                  | 0x03558F692031D58C| 0x91CAC70AC2792E2A| 0x2A8  | 5 (+1)
- [x] GcRewardUnlockSeasonReward                         | 0xE6212DF525ECA350| 0x7AB9EBA17278DE9B| 0x40   | 5 (-1)
- [x] GcSeasonalMilestoneEncryption                      | 0xD85DFF8ADAEB741D| 0x9562AF9028346F05| 0x180  | 7 (-3)
- [ ] GcSmokeBotPlanetReport                             | 0xA45C8D02FAACDDE6| 0x778378F86BB2392C| 0xB0   | 2 (+2)
- [ ] GcSmokeBotReport                                   | 0x3BC2543792E9B519| 0x16AC643981D10CC9| 0x18   | 2 (+2)
- [ ] GcSmokeBotStats                                    | 0x2608B5B9ED8DC24B| 0xBF03A94511E0F7B0| 0xA0   | 16 (+16)
- [ ] GcSmokeBotSystemReport                             | 0x45A0E050DAB66262| 0xFB50309B36475BDE| 0x160  | 4 (+4)
- [ ] GcTestMetadata                                     | 0xED9D01EDEE998FDB| 0xCE965FAFD6BBF99E| 0x6E0  | 35 (+1)
- [ ] TkAnimNodeData                                     | 0x14C032849E45EE8D| 0x6E19250A34E2CE86| 0x50   | 5 (-1)
- [ ] TkIndexStream                                      | 0x0C3F2CB3BC1F3270| 0x4E6048B326CC903A| 0x10   | 1 (+1)
- [ ] TkMaterialResource                                 | 0xFD4EC7E71CA16A38| 0x75EC92F2E9E3196F| 0x84   | 2 (+1)
- [ ] TkModelResource                                    | 0x83447CE313934E8F| 0xBE5E5CB33D0EB022| 0x84   | 2 (+1)
- [ ] TkTextureResource                                  | 0x8F308DA13045525E| 0x2316F23520D820A9| 0x84   | 2 (+1)
- [ ] TkVertexStream                                     | 0xF7FE8408BD5A0B28| 0x63E16E6AF89FE439| 0x10   | 1 (+1)

**Comment by monkeyman192** [comment]
Just going to do my own shorter list here too to keep track of the changes just due to this recent update...

## New structs:

- [x] GcFrigateFlybyLayout	0x68D6ADC8973A8BF8
- [x] GcFrigateFlybyOption	0xA9C452E692D856B7
- [x] GcFrigateFlybyTable	0x1BC220B7D70D6004
- [x] GcFrigateFlybyType	0xA63ABD9C5969E9A1
- [x] GcMessageRequestWarp	0x5080D27AD07FC174
- [x] GcMissionConditionIsFrigateFlybyActive	0x15672C9CC175CDF0
- [x] GcMissionConditionSeasonRewardUnlocked	0x159F8012EE621439
- [x] GcRewardFrigateFlyby	0x9CDBB49E1C4E9525
- [x] GcRewardSpecificFrigate	0x3CE3CF6A59E14C41

## Structs with internal changes:

- [x] GcAISpaceshipManagerData	0x27738D5716A1FB02
- [x] GcAISpaceshipModelData	0xACC95E89FA8B8306
- [x] GcAISpaceshipModelDataArray	0xECD8F09878355A02
- [x] GcAISpaceshipPreloadCacheData	0x52E86888EF0146C8
- [x] GcAISpaceshipPreloadList	0x2FDB641166F3E987
- [x] GcAlienPuzzleEntry	0x3914B6AF0B456EE9
- [x] GcAlienPuzzleOption	0xAD838ACFAF4B61E2
- [x] GcAlienPuzzleTable	0x73943B7498328DAA
- [x] GcAudioAreaTriggerComponentData	0xB057FFF3C769B827
- [x] GcAudioWwiseEvents	0x2F24A9D0DAC75975
- [x] GcConsumableItem	0xC22686ED58582AC2
- [x] GcConsumableItemTable	0xE35B0F0E2C3AA549
- [x] GcCostFleetStoredIncome	0x4DE6495E6CC1A1BB
- [x] GcCreatureCrystalMovementData	0xF1C165FC6FB9B413
- [x] GcCreatureCrystalMovementDataParams	0x93942165FC7A8362
- [x] GcDefaulMissionProduct	0x602DB248C9FAB5D3
- [x] GcDefaultMissionItemsTable	0xF8A034C1AFF5BA89
- [x] GcDefaultSaveData	0xB5E5FA44A8496075
- [x] GcExpeditionPowerup	0xF42149E3C1B01929
- [x] GcExperienceDebugTriggerAction	0x77594A70CC1F1130
- [x] GcExperienceDebugTriggerActionTypes	0xA8D2F2D63EE6EAD6
- [x] GcExperienceDebugTriggerInput	0x18ACF638FAAEC9EA
- [x] GcExplosionDataTable	0x649C5A4B22C88C20
- [x] GcFleetFrigateSaveData	0x1244A53919988284
- [x] GcFrigateClass	0x4EA913E3A4D76E25
- [x] GcFrigateStatType	0x5756163EE10E2CBB
- [x] GcFrigateTraitData	0xB182431F45859CBA
- [x] GcFrigateTraitTable	0x74F2737E186F2AFD
- [x] GcGalaxyAudioSetupData	0x6CE41E7D383BAA01
- [x] GcGenericMissionSequence	0x8C5CCFEA425668CE
- [x] GcGrabPlayerComponentData	0x6D091499DCEB214D
- [x] GcHUDStartup	0x27764934F8C62B1B
- [x] GcHUDStartupTable	0x186B16D88BC8860D
- [x] GcInventorySlotActionData	0xE345C9231071BCBA
- [x] GcLaserBeamData	0x940B61A1D3CEBB8E
- [x] GcMissionConditionHasProduct	0x1B4B3546967A9DC6
- [x] GcMissionConditionProductKnown	0x274F1A5C749A0EBA
- [x] GcMissionSequenceAudioEvent	0x3990F92BE11AA5C0
- [x] GcMissionSequenceCollectProduct	0xEBD2718D2F912DE4
- [x] GcMissionSequenceCommunicator	0x846EFB7DEC4B2114
- [x] GcMissionSequenceDetailMessage	0x24B2FB46F1D69264
- [x] GcMissionSequenceShowMessage	0xD93EA1F427C3D9
- [x] GcMissionTable	0x65C340F441ABE4CE
- [x] GcPlayerCommunicatorMessage	0x4D2440DFB146AE13
- [x] GcPlayerCommunicatorMessageWeighted	0x92CA66BB08052620
- [x] GcPlayerStateData	0x2E3F4435E9C8FE7F
- [x] GcProjectileData	0x47809F6F80D413D0
- [x] GcProjectileDataTable	0x1ECFA675D59D771A
- [x] GcPulseEncounterInfo	0x481358C9DD885704
- [x] GcPulseEncounterSpawnTrader	0xAE168EB8E846799D
- [x] GcRewardCommunicatorMessage	0xA4CCC2F6A734A389
- [x] GcRewardOSDMessage	0x686C3DD252BAB451
- [x] GcRewardSecondaryInteractionOptions	0x679D088DCE85CA04
- [x] GcScanEventData	0xC94E09D75F416150
- [x] GcScanEventTable	0xA99FE6E20CF26800
- [x] GcSeasonalGameModeData	0x82EDCC2C4DAB7F03
- [x] GcShipDialogue	0xF653BDA2ED60AE1D
- [x] GcSolarSystemData	0xC0571B235E7E1966
- [x] GcUnlockableSeasonRewards	0x4F532B760AFC9261
- [x] GcWeatherEffect	0x9F315BB206C6CFB4
- [x] GcWeatherEffectTable	0x52DDAE4F92AE369
- [x] gcproducttableEnum	0xBFB540E00EF4F2F9

## Structs with a file size change:

- [ ] GcAISpaceshipGlobals	old: 0x0DD0	new: 0x0E30	GUID: 0x799F4D491CC28E95	fields: 346 (+1)	
- [x] GcDebugScene	old: 0x1AB0	new: 0x1AD0	GUID: 0x7E25C7AEC48DD019	fields: 51 (+4)	
- [x] GcExperienceSpawnTable	old: 0x110	new: 0x120	GUID: 0x72EE84117BBBC18E	fields: 18 (+1)	
- [ ] GcFleetGlobals	old: 0x16B0	new: 0x1910	GUID: 0x284B5EBC189D518E	fields: 136 (+9)	
- [ ] GcPlayerGlobals	old: 0x1C80	new: 0x1CA0	GUID: 0xEF116EB2C021600F	fields: 843 (+3)	

## Structs with a field number changes:

- [x] GcExplosionData	old: 0xC8	new: 0xC8	GUID: 0x31F4B7FF54348572	fields: 15 (+1)	
- [x] GcUnlockableSeasonReward	old: 0x38	new: 0x38	GUID: 0x2A4CED29CC453DF1	fields: 5 (+1)

**Comment by HolterPhylo** [comment]
No problem, I leave it to you in the future

**Comment by HolterPhylo** [comment]
GcAISpaceshipGlobals DONE

**Comment by HolterPhylo** [comment]
I had removed my previous list so it was clearer to use your list.  

Unfortunately:

Your list is not listing some struct changes (Size change without GUID change) that are important to make MBINCompiler correctly create these struct.  So I created a  'shorter' list to be able to find and check them (ex. GcFrigateTraitIcons, GcPassiveFrigateIncomeArray, GcFrigateTraitStrengthByType,  ...) to name a few

**Comment by monkeyman192** [comment]
> 
> 
> I had removed my previous list so it was clearer to use your list.
> 
> Unfortunately:
> 
> Your list is not listing some struct changes (Size change without GUID change) that are important to make MBINCompiler correctly create these struct. So I created a 'shorter' list to be able to find and check them (ex. GcFrigateTraitIcons, GcPassiveFrigateIncomeArray, GcFrigateTraitStrengthByType, ...) to name a few

Thanks! I didn't realise this and have updated my script to include this now!
