### ISSUE TITLE
Could we have a NMSString0x800 so there is no exception like in GcDebugOptions ?

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#337]
Could we have a NMSString0x800 so there is no exception like in GcDebugOptions ?

>     [NMS(Size = 0x800, Alignment = 0x1)]
>     public class NMSString0x800 : NMSTemplate
>     {
>         [NMS(Size = 0x800)]
>         public string Value;
>     }
> 

    public class GcDebugOptions : NMSTemplate
    {
        ...
        /* 0x1325 */ public bool AutoJoinUserEnabled;
        [NMS(Size = 0x8)]
        /* 0x1326 */ public NMSString0x100[] AutoJoinUserNames;      // this is its own struct now but this should work...
        /* 0x1B26 */ public bool AlwaysSaveGameAsClient;

**Comment by monkeyman192** [comment]
I don't think it's actually a 0x800 length string though is it? IIRC in the exe it's an array of length 8, but the object I think looked like a NMSString0x100 but I don't think it is. It was a while ago since I looked at this though...
Edit: Looking at the exe again I see that it doesn't actually have an array of length 8... no idea why I put it like that originally...
In the exe it does indeed look like it should be NMSString0x800, so I think it would be good to change it. I'll wait until I have the string changes merged though before making the change I think...
