### ISSUE TITLE
.NET 6.0

### ISSUE THREAD

**Issue by Kobi-Blade** [monkeyman192/MBINCompiler#478]
.NET 5.0 is no longer supported by Microsoft and causes major issues on Windows 11 (explorer.exe pretty much hangs if you install .NET 5.0).

Are there any plans to use .NET 6.0 instead?

**Comment by monkeyman192** [comment]
There is indeed! Once this current update cycle has slowed down and we have got the compiler working for it I'll be drafting up a plan to standardise the naming of the binaries produced. This proposal will include generating a binary for .net 6 as well.
This is maybe a few weeks away due to a number of factors, but it is definitely something we are planning on doing soon 😄

**Comment by Kobi-Blade** [comment]
It's alright I can wait, is just been bothersome to try and MOD NMS in Windows 11, as most tools don't work on it natively.

**Comment by monkeyman192** [comment]
We include a .net4 libmbin dll which may have better compatibility. Tbh I hate how much of a mess the dotnet ecosystem is in terms of versions...

**Comment by HolterPhylo** [comment]
What is your win 11 version?

**Comment by Kobi-Blade** [comment]
22H2 build 22621.232, it does not support .NET 5.0 it will just hang the explorer.exe constantly.

PSARCTool also doesn't work cause it doesn't take into account the new Terminal, I had to use the original PSARC.

Then I got stuck not being to use MBINCompiler due to .NET 5.0, I had to run it as monkey suggested through libmbin, but it doesn't support the file I was trying to decrypt yet.

**Comment by HolterPhylo** [comment]
I guess you have your reasons for running windows 11 cutting edge preview code like this:

> Windows 11 version 22H2 update KB5015818 arrived in the RP channel and served via Windows Update. Users can also manually download the update and install it on their system to update the build number to 22621.232.

> IMPORTANT
This KB update is not yet available in the Microsoft catalog.
Served via Windows update to 22621 build users, Version 22H2.

But I would not say that windows 11 `.NET 5.0 is no longer supported by Microsoft... ` based on that

![image](https://user-images.githubusercontent.com/3037251/180338790-b3db6bcb-3b84-4fae-90d7-9ac82c744ada.png)

**Comment by Kobi-Blade** [comment]
> I guess you have your reasons for running windows 11 cutting edge preview code like this:
> 
> > Windows 11 version 22H2 update KB5015818 arrived in the RP channel and served via Windows Update. Users can also manually download the update and install it on their system to update the build number to 22621.232.
> 
> > IMPORTANT
> > This KB update is not yet available in the Microsoft catalog.
> > Served via Windows update to 22621 build users, Version 22H2.
> 
> But I would not say that windows 11 `.NET 5.0 is no longer supported by Microsoft... ` based on that
> 
> ![image](https://user-images.githubusercontent.com/3037251/180338790-b3db6bcb-3b84-4fae-90d7-9ac82c744ada.png)

This is a RTM build which is what you getting with 22H2, so it makes total sense to use it to see how Software runs on 22H2 and how you can fix it.

Not to mention I never said .NET 5.0 is not supported based on that, https://dotnet.microsoft.com/en-us/download/dotnet/5.0

In case you miss the red banner,
> This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [.NET 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) for more details.

**Comment by HolterPhylo** [comment]
Just quoted your opening comment:
![image](https://user-images.githubusercontent.com/3037251/180341707-58017161-b5f0-4ea2-b471-09087b9e1eb5.png)

**Comment by Kobi-Blade** [comment]
> Just quoted your opening comment: ![image](https://user-images.githubusercontent.com/3037251/180341707-58017161-b5f0-4ea2-b471-09087b9e1eb5.png)

Please stop walking in circles with poor arguments, this is not a Forum.

Unless you have something intelligent to contribute to the discussion or .NET 6.0 implementation refrain from posting here.

Plus as stated by @monkeyman192 and well, .NET 6.0 is a LTS release, which means has an extended support cycle.

**Comment by cmkushnir** [comment]
I'm surprised that you are finding major issues w/ .NET 5 and Windows 11.  I haven't tested that combo, but according to MS .NET 5 is supported under Win11: [https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md)
I have seen issues w/ win11 updates breaking some net versions, mainly 3.5, but those are just normal issues that tend to happen now and then and are usually resolved by a subsequent update.  I haven't found anything that says .NET 5 isn't supported under Win11 or that it shouldn't be used.
I agree .NET 6 would be a better option going forward, but that isn't because of .NET 5 and Win11 compat issues.

**Comment by Kobi-Blade** [comment]
> I'm surprised that you are finding major issues w/ .NET 5 and Windows 11. I haven't tested that combo, but according to MS .NET 5 is supported under Win11: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md I have seen issues w/ win11 updates breaking some net versions, mainly 3.5, but those are just normal issues that tend to happen now and then and are usually resolved by a subsequent update. I haven't found anything that says .NET 5 isn't supported under Win11 or that it shouldn't be used. I agree .NET 6 would be a better option going forward, but that isn't because of .NET 5 and Win11 compat issues.

You have all the information you need on the same source you posted, https://github.com/dotnet/core/tree/main/release-notes/5.0

>**.NET 5 Release -- Out of Support**
>This release is out of support. See [.NET releases](https://github.com/dotnet/core/blob/main/releases.md) for in-support releases.
>[.NET 5](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) was released on May 10, 2020. The release was a collaborative effort by many contributors. [.NET 5 reached end of support on May 10, 2022](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/) | It was [supported by Microsoft](https://github.com/dotnet/core/blob/main/microsoft-support.md) on [multiple operating systems](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md).

If you need further guidance on supported .NET releases, https://github.com/dotnet/core/blob/main/releases.md

.NET 5 is not supported since May 10, issues on Windows 11 22H2 are to be expected since it's releasing outside the .NET 5 support window.

Plus the testing was done on a clean system, the moment .NET 5 was installed the explorer.exe stopped working, it resumed normal operations after uninstalling .NET 5.

Reliability monitor also [confirms](https://imgur.com/a/tIaCc2n) this, meanwhile I found more people who had exactly the same issue on 22H2 with .NET 5 with no fix so far.

**Comment by cmkushnir** [comment]
I'm not saying you aren't having issues, I'm saying the official MS position is that .NET 5 is supported on Win11.  Statements about what is to be expected or what current issues may currently exist don't invalidate that official position.  .NET 5 and Win7 is also a supported combo and yet Win7 has been out of support for a while, out of support isn't black-and-white like you seem to be suggesting.

**Comment by BSarmady** [comment]
Hmmm, Dropping my two cents here, 

Since releases of .net core are going out of support very fast, (every 2 years) I would say it doesn't worth updating the code to it.
According to same github repo, .NET 6 will go out of support in Nov 2024 and .NET 7 Preview will go out of support in May 2024. 

Just a side note, most software products had 5 years support (10 years for LTS) and Microsoft was the first company to put out a max 2 years support and then others followed.

https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

Since .NET 4 is part of OS and will be as long as a product called Windows is published, I would say lets roll back to .NET 4 which also has a benefit on not having to install any runtime libraries.

Since @Kobi-Blade has proficiency in C++ perhaps he can help to translate the entire thing to C++ as it is a better option that exists since beginning of time and and will be supported until end of time.

**Comment by monkeyman192** [comment]
Ok, so this issue has been closed since I merged the above linked PR.
From this point onwards there will be a .net6 libmbin produced and released also. It will then be up to other tool developers to support .net 6
