### ISSUE TITLE
Floating point precision difference between MBINCompiler and libMBIN

### ISSUE THREAD

**Issue by Babscoole** [monkeyman192/MBINCompiler#505]
There's a difference in the last one or two digits for longer floats, depending on whether the file was decompiled with MBINCompiler or libMBIN.  This can make differential comparisons of EXML files from decompiling with the two available methods much more difficult.  Example EXMLs (added .txt so they would upload) added.  Same MBIN, one decompiled with MBC, the other libmbin.  
[NMS_REALITY_GCPRODUCTTABLE-mbncompiler.EXML.txt](https://github.com/monkeyman192/MBINCompiler/files/9355294/NMS_REALITY_GCPRODUCTTABLE-mbncompiler.EXML.txt)
[NMS_REALITY_GCPRODUCTTABLE-libmbin.EXML.txt](https://github.com/monkeyman192/MBINCompiler/files/9355296/NMS_REALITY_GCPRODUCTTABLE-libmbin.EXML.txt)

**Comment by cmkushnir** [comment]
Pretty sure they both call the same code:
```
                case "Single":
                    // prefer the default, short-form string format
                    valueString = ((float) value).ToString( System.Globalization.CultureInfo.InvariantCulture);
                    if ( float.Parse( valueString ) != (float) value ) { // the default string format may not be accurate
                        // if it's not accurate enough, then use the full-precision format
                        valueString = ((float) value).ToString( "G9", System.Globalization.CultureInfo.InvariantCulture );
                    }
                    break;
```
How did you generate the libmbin exml ?

**Comment by Babscoole** [comment]
MBIN to EXML via NMSPE, so maybe it's an issue with the .net 4 version only.

Did some further testing.  Decompiled latest NMS_REALITY_GCPRODUCTTABLE.MBIN to EXML by multiple methods.  MBINCompiler, .net5 libMBIN.dll via NMSMB, and .net4 libMBIN.dll via NMSPE.  NMSMB and MBINCompiler were a match.  NMSPE long floats were wackadoo for the last one or two digits.  So, guessing that .net 4 is interpreting things slightly different.  The problem with this is a ton of people use NMSPE to extract/decompile the game files.

**Comment by cmkushnir** [comment]
"The problem with this is a ton of people use NMSPE to extract/decompile the game files." ... well they should stop that.  :)

A float only has 6 or 7 digits of precision: https://en.wikipedia.org/wiki/Single-precision_floating-point_format so if you see a string version of a float with more that 6 or 7 digits (ignoring any leading 0's) it's wrong.

One option would be to have mbinc only write 6 sig dig instead of just using .ToString( System.Globalization.CultureInfo.InvariantCulture)

.NET Core uses: https://source.dot.net/#System.Private.CoreLib/Number.Formatting.cs,679ab5323fc79b90

.NET Framework uses: https://referencesource.microsoft.com/#mscorlib/system/number.cs,f4a2bf2ab599b727 which unfortunately uses an internal (c) function to do the conversion, so can't check what it does diff.

Rounding to sig dig isn't really built-in, the closest would be using the G notation e.g. G6 formatting will write 123456789 like 1.23456E8.  See: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?redirectedfrom=MSDN#GFormatString

... actually, just noticed in the mbinc code the G9 option, which may be causing issues, should probably be G6 or G7 at most.  Should check what double's are using as well, they have around 17 sig dig ... yeah mbinc is using G17 for doubles.
So maybe we could try a build with G6 or G7 for single and you could test again.

**Comment by cmkushnir** [comment]
... added wrinkle: https://docs.microsoft.com/en-us/dotnet/api/system.single?view=net-6.0
"A Single value has up to 7 decimal digits of precision, although a maximum of 9 digits is maintained internally." so that's likely where G9 came from.

**Comment by Babscoole** [comment]
See what MM and Wbertro think, but I think everyone would agree that a goal should be identical output, regardless of MBC, .net 5 libMBIN or .net 4 libMBIN

**Comment by cmkushnir** [comment]
"In this case, the values can be successfully round-tripped by using the "G9" standard numeric format string to preserve the full precision of Single values ..."

**Comment by Babscoole** [comment]
All the differentiation I'm seeing are in the 8th and 9th digit, so 7 or even 6 would be more than sufficient.

**Comment by cmkushnir** [comment]
Unfortunately the mbinc code looks correct for both .NET 4.7.2 and .NET 6:

.NET 4.7.2: https://docs.microsoft.com/en-us/dotnet/api/system.single?view=netframework-4.7.2
.NET 6: https://docs.microsoft.com/en-us/dotnet/api/system.single?view=net-6.0

In both cases the doc's state: "the values can be successfully round-tripped by using the "G9" standard numeric format string to preserve the full precision of Single values"

**Comment by cmkushnir** [comment]
I guess .NET 4 and 6 use different mechanism to maintain the extra 2 digits.  We may want to just try using G7, and if that produces the same for all then may be good enough.  The case for concern would be where something may not round-trip from mbin to exml back to mbin back to exml - comparing the 2 exml's|mbin's may show diff's between floats that weren't changed.

**Comment by cmkushnir** [comment]
... or maybe convert the float to a double then use G9 on the double ... though that may not be quite correct and may cause it's own round-trip issues.

would guess may have same issue with G17 for doubles.

**Comment by cmkushnir** [comment]
Also need to verify which conversion is being used:
((float) value).ToString( System.Globalization.CultureInfo.InvariantCulture);
or 
((float) value).ToString( "G9", System.Globalization.CultureInfo.InvariantCulture );

If it's the first then may need to remove that and always use G.  But then all floats|doubles will be exported in exponential format.

**Comment by HolterPhylo** [comment]
Something strange comparing the 2 files that @Babscoole posted at the top (and that I can reproduce exactly) with all flavors
```
2471 <Property name="Colour" value="Colour.xml">
2472       <Property name="R" value="0.101960786" />
2473       <Property name="G" value="0.15294118" />
2474       <Property name="B" value="0.2" />
2475       <Property name="A" value="1" />
2476 </Property>
```
**Why is line 2472 9 decimals in ALL versions (.net5 and .net4) but line 2473 is only 8 decimals in .net5 and 9 decimals in NMSPE .net4 ?**

These are 1) NMS_REALITY_GCPRODUCTTABLE-mbncompiler.EXML.txt on the left,
2) NMS_REALITY_GCPRODUCTTABLE-libmbin.EXML.txt on the right:
![Screenshot - 8_27_2022 , 5_44_14 PM](https://user-images.githubusercontent.com/3037251/187049024-8fa48b4d-baad-4f3b-baad-686a2b433c3f.png)

this is from NMSPE:
![Screenshot - 8_27_2022 , 5_30_27 PM](https://user-images.githubusercontent.com/3037251/187048731-218f6671-3b8c-49e3-8783-bc2e75749cd9.png)

**Comment by cmkushnir** [comment]
A 4 byte float only has about 7 sig dig.  However, .NET (4 and 6) somehow stores an extra 2 digits, likely to reduce propagation of rounding errors during intermediate calculations.  The issue is that how .NET 4 and 6 manage those extra 2 digits seems to be different.  Different means in some cases they may have the same value and in some cases different.  I haven't looked into how they manage those extra 2 digits, I'm saying this based on their doc's (previously linked).
The difference of 8 digits vs 9 digits may just be that the 8 digit value only needs 8 digits to be exactly represented:
https://en.wikipedia.org/wiki/Single-precision_floating-point_format

**Comment by cmkushnir** [comment]
As mentioned, more important than the actual sig dig's (number of them or the actual value) is that mbin to exml to mbin to exml round-trips and does not introduce any changes to unedited floats i.e. no changes in the 4 bytes.

**Comment by Babscoole** [comment]
Currently have a .net 5 version of NMSPE waiting in the wings for release soon with AMUMSS 4.0 (with preparations for a .net 6 version when the time comes), So .net 4 version of libMBIN will no longer be necessary.  :)
