### ISSUE TITLE
NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE

### ISSUE THREAD

**Issue by ShinSakanami** [monkeyman192/MBINCompiler#89]
There's differences in result when NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE is decompiled with MBINCompiler 1.58/1.59-pre1 and 1.58-pre1.

Sample with 1.58-pre1, line 89:
```
<Property name="Quality" value="Rare" />
<Property name="Category" value="GcProceduralTechnologyCategory.xml">
    <Property name="ProceduralTechnologyCategory" value="Mining" />
</Property>
<Property name="NumStatsMin" value="2" />
<Property name="NumStatsMax" value="3" />
<Property name="WeightingCurve" value="GcWeightingCurve.xml">
    <Property name="WeightingCurve" value="MaxIsRare" />
</Property>
```
Sample with 1.58 and 1.59-pre1, line 89:
```
<Property name="Quality" value="Rare" />
<Property name="NumStatsMin" value="2" />
<Property name="NumStatsMax" value="2" />
<Property name="WeightingCurve" value="GcWeightingCurve.xml">
    <Property name="WeightingCurve" value="MaxIsSuperRare" />
</Property>
```
It's the same thing with every item in the table: with 1.59-pre1 and 1.58, the "Category" property is missing, and properties "NumStatsMin", "NumStatsMax" and "WeightingCurve" are often different.

**Comment by WTM-Tech** [comment]
Besides the Category property missing several of the NumStatsMin and NumStatsMax appear to be reversed.  For Example all of the UP_SCAN1 through UP_SCAN3 IDs have them reversed.

I modified the UP_SHLD3 section as show below and it seems to break the item in game.  There are only 2 stats possible for the shield upgrade yet it has NumStatsMin=4 and NumStatsMax=2.  I would have thought going to 2 and 2 with "NoWeighting" would be a safe change, but it seems to break the upgrade.  The in game the description of the upgrade has the actual text "UP_SHIELDBOOST3_DESC" instead of the stat values as usual.

I'm going to try and just decompile and recompile and see if the upgrade item is still broke.  I'll post later with results.

----- Original 1.5.9.0 decompiled lines
`   <Property name="ID" value="UP_SHLD3" />
   ...
   <Property name="NumStatsMin" value="4" />
   <Property name="NumStatsMax" value="2" />
   <Property name="WeightingCurve" value="GcWeightingCurve.xml">
      <Property name="WeightingCurve" value="MaxIsRare" />
   </Property>
`

----- Modified 1.5.9.0 lines then recompiled and added to pack.
`
   <Property name="ID" value="UP_SHLD3" />
   ...
   <Property name="NumStatsMin" value="2" />
   <Property name="NumStatsMax" value="2" />
   <Property name="WeightingCurve" value="GcWeightingCurve.xml">
      <Property name="WeightingCurve" value="NoWeighting" />
   </Property>
`

**Comment by WTM-Tech** [comment]
A decompile and recompile of NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE with no edits seems to be fine.  So for now I'll just leave the NumStatsMin and NumStatsMax reversed and test with just the stat changes I had from my 1.5.8 and 1.5.7 MOD pack.

**Comment by GaticusHax** [comment]
Thanks. I'll check it out.

**Comment by GaticusHax** [comment]
This is now fixed in the source code and should work in the next release.
Thanks.

**Comment by ShinSakanami** [comment]
Glad to help, and thanks for your work on this tool :)
