### ISSUE TITLE
ProjectileTable crashes the game when recompiled

### ISSUE THREAD

**Issue by trevizor** [monkeyman192/MBINCompiler#94]
Simply decompiling and recompiling the projectile table mbin file will cause the game to crash upon projectile creation. I.E. Firing your multitool

Attached is a recompiled file without any edits to the XML file.

METADATA\PROJECTILES\PROJECTILETABLE.MBIN
[PROJECTILETABLE.zip](https://github.com/monkeyman192/MBINCompiler/files/2403501/PROJECTILETABLE.zip)

MBIN COMPILER: v1.59.0-pre2
NMS: 1.60 (1.59.x as well)

**Comment by monkeyman192** [comment]
I tried one of the drone entities you attached and it recompiles perfectly for me 0 difference when doing a byte-wise comparison... (that's with 1.59.0-pre2)
Haven't look at other files yet...

**Comment by trevizor** [comment]
After decompiling a recompiled file, all  BehaviourFlags values are replaced with -1 on the exml.

**Comment by monkeyman192** [comment]
this looks to be due to a few issues:
 - List serialisation is again (@Fuzzy-Logik what do you do to it?!?) not putting things in the correct order.
 - Alignment of data within a struct should be relative to the start of the struct, not the start of the file.
I think fixing both these issues should give us flawless recompilation of lists once and for all...
